#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the countTriplets function below.
def countTriplets(arr, r):
    count=0
    bf={}
    af={}
    for v in arr:
        if v in af:
            af[v]+=1
        else:
            af[v]=1
    for v in arr:
        af[v]-=1
        if v//r in bf and v%r==0 and v*r in af:
            count+=bf[v//r]*af[v*r]
        if v in bf:
            bf[v]+=1
        else:
            bf[v]=1
    return count



nr = input().rstrip().split()
n = int(nr[0])
r = int(nr[1])
arr = list(map(int, input().rstrip().split()))
ans = countTriplets(arr, r)
print(str(ans) + '\n')





                                                                                    JAVA
    import java.io.*;
import java.math.*;
import java.security.*;
import java.text.*;
import java.util.*;
import java.util.concurrent.*;
import java.util.function.*;
import java.util.regex.*;
import java.util.stream.*;
import static java.util.stream.Collectors.joining;
import static java.util.stream.Collectors.toList;

public class Solution {

    // Complete the countTriplets function below.
    static long countTriplets(List<Long> arrlist, long r) 
    {
        long count=0;
        Map<Long,Long> bf=new TreeMap<>();
        Map<Long,Long> af=new TreeMap<>();
        Long[] arr = new Long[arrlist.size()];
        arr = arrlist.toArray(arr);
        long one=1;
        for(int i=0;i<arr.length;i++)
        {
            if(af.containsKey(arr[i]))
            {
                af.put(arr[i],af.get(arr[i])+one);
            }
            else
            {
                af.put(arr[i],one);
            }
        }
        for(int i=0;i<arr.length;i++)
        {
            af.put(arr[i],af.get(arr[i])-1);
            if(bf.containsKey(arr[i]/r) && arr[i]%r==0 && af.containsKey(arr[i]*r))
            {
                count+=bf.get(arr[i]/r)*af.get(arr[i]*r);
            }
            if (bf.containsKey(arr[i]))
            {
                bf.put(arr[i],bf.get(arr[i])+one);
            }
            else
            {
                bf.put(arr[i],one);
            }
        }
        return count;
        
    }

    public static void main(String[] args) throws IOException {
        BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(System.in));
        
        String[] nr = bufferedReader.readLine().replaceAll("\\s+$", "").split(" ");

        int n = Integer.parseInt(nr[0]);

        long r = Long.parseLong(nr[1]);

        List<Long> arr = Stream.of(bufferedReader.readLine().replaceAll("\\s+$", "").split(" "))
            .map(Long::parseLong)
            .collect(toList());

        long ans = countTriplets(arr, r);

        System.out.println(String.valueOf(ans));
        
    }
}


