#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the stepPerms function below.
result=dict()
result[1]=1
result[2]=2
result[3]=4
def stepPerms(n):
    if n==0:
        return 0
    if n in result.keys():
        return result[n]
    result[n]=stepPerms(n-3)+stepPerms(n-2)+stepPerms(n-1)
    return result[n]
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = int(input())

    for s_itr in range(s):
        n = int(input())

        res = stepPerms(n)

        fptr.write(str(res) + '\n')

    fptr.close()
#Rijushree
